samples: samples.tsv
units: units.tsv
known_sites: /hpcdata/bcbb/karlinser/Projects/NEMO/known_sites.vcf.gz

ref:
  name: GRCh37.75
  # Path to the reference genome, ideally as it is provided by the GATK bundle.
  genome: /hpcdata/bcbb/karlinser/Projects/NEMO/mask_fasta/human_g1k_v37_decoy_IKBKGP1_masked.fasta
  # Path to any database of known variants, ideally as it is provided by the GATK bundle.
  known-variants: /hpcdata/bio_data/current/GATK/bundle/2.8/b37/dbsnp_138.b37.vcf.gz
  gatk3_jar: /sysapps/cluster/software/GATK/3.8.1-Java-1.8.0_92/GenomeAnalysisTK.jar

focused-genotyping:
  known_sites: true
  putative: true

filtering:
  # Set to true in order to apply machine learning based recalibration of
  # quality scores instead of hard filtering.
  vqsr: false
  hard:
    # hard filtering as outlined in GATK docs
    # (https://gatkforums.broadinstitute.org/gatk/discussion/2806/howto-apply-hard-filters-to-a-call-set)
    snvs:
      "QD < 2.0 || FS > 60.0 || MQ < 40.0 || MQRankSum < -12.5 || ReadPosRankSum < -8.0"
    indels:
      "QD < 2.0 || FS > 200.0 || ReadPosRankSum < -20.0"

processing:
  remove-duplicates: true
  # Uncomment and point to a bed file with, e.g., captured regions if necessary,
  # see https://gatkforums.broadinstitute.org/gatk/discussion/4133/when-should-i-use-l-to-pass-in-a-list-of-intervals.
  restrict-regions: /hpcdata/bcbb/karlinser/Projects/NEMO/IKBKG.bed
  # If regions are restricted, uncomment this to enlarge them by the given value in order to include
  # flanking areas.
  # region-padding: 100

params:
  gatk:
    HaplotypeCaller:
      ploidy:
        "-ploidy 4"
      known:
        "-ploidy 4 --output_mode EMIT_ALL_SITES --genotyping_mode GENOTYPE_GIVEN_ALLELES"
    BaseRecalibrator: ""
    GenotypeGVCFs: "--java-options \"-Xmx200G\" -ploidy 4 -L X:153769495-153795321"
    VariantRecalibrator: ""
  known_sites:
    vcf: /hpcdata/bcbb/karlinser/Projects/NEMO/known_sites.vcf.gz
  putative:
    chrom: X
    start: 153788571
    end: 32008435
    min_alt: 2
    vcf_for_header: /hpcdata/bcbb/karlinser/Projects/NEMO/known_sites.vcf.gz
  picard:
    MarkDuplicates: "REMOVE_DUPLICATES=true"
  trimmomatic:
    pe:
      trimmer:
        # See trimmomatic manual for adding additional options, e.g. for adapter trimming.
        - "LEADING:3"
        - "TRAILING:3"
        - "SLIDINGWINDOW:4:15"
        - "MINLEN:36"
        - "-phred33"
    se:
      trimmer:
        # See trimmomatic manual for adding additional options, e.g. for adapter trimming.
        - "LEADING:3"
        - "TRAILING:3"
        - "SLIDINGWINDOW:4:15"
        - "MINLEN:36"
